agency/urls.py
from django.urls import path

from agency.views import (
    index,
    TopicListView,
    RedactorListView,
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("articles/", ArticleListView.as_view(), name="article-list"),

    path(
        "articles/<int:pk>/",
        ArticleDetailView.as_view(),
        name="article-detail"
    ),

    path(
        "articles/create/",
        ArticleCreateView.as_view(),
        name="article-create"
    ),

    path(
        "articles/<int:pk>/update",
        ArticleUpdateView.as_view(),
        name="article-update"
    ),

    path(
        "articles/<int:pk>/delete",
        ArticleDeleteView.as_view(),
        name="article-delete"
    ),

]

app_name = "agency"

auto_news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agency/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("agency:redactor-detail", kwargs={"pk": self.pk})


class Article(models.Model):
    title = models.CharField(max_length=127, unique=True)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(to=Topic, on_delete=models.DO_NOTHING)
    publishers = models.ManyToManyField(to=Redactor, related_name="articles")

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("agency:article-detail", kwargs={"pk": self.pk})

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model

from agency.models import Article


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class ArticleSearchForm(forms.Form):
    title = forms.CharField(
        max_length=127,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )


class ArticleForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Article
        fields = "__all__"


agency/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from agency.forms import (
    TopicSearchForm,
    RedactorSearchForm,
    ArticleSearchForm,
    ArticleForm,
)
from agency.models import Redactor, Article, Topic


@login_required
def index(request):
    num_redactors = Redactor.objects.count()
    num_articles = Article.objects.count()
    num_topics = Topic.objects.count()

    contex = {
        "num_redactors": num_redactors,
        "num_articles": num_articles,
        "num_topics": num_topics,
    }

    return render(request, "agency/index.html", context=contex)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "agency/topic_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        contex = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        contex["search_form"] = TopicSearchForm(initial={"name": name})
        return contex

    def get_queryset(self):
        queryset = Topic.objects.all().order_by("id")
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    template_name = "agency/redactor_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        contex = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        contex["search_form"] = (
            RedactorSearchForm(initial={"username": username})
        )
        return contex

    def get_queryset(self):
        queryset = Redactor.objects.all().order_by("id")
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class ArticleListView(LoginRequiredMixin, generic.ListView):
    model = Article
    paginate_by = 5
    template_name = "agency/article_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        contex = super(ArticleListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        contex["search_form"] = ArticleSearchForm(initial={"title": title})
        return contex

    def get_queryset(self):
        queryset = Article.objects.all().select_related("topic").order_by("id")
        form = ArticleSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset


class ArticleDetailView(LoginRequiredMixin, generic.DetailView):
    model = Article


class ArticleCreateView(LoginRequiredMixin, generic.CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy("agency:article-list")


class ArticleUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy("agency:article-list")


class ArticleDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Article
    success_url = reverse_lazy("agency:article-list")

templates/agency/article_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>Delete article?</h1>
        </div>
      </div>
    </div>
    {% load static %}
  </section>
  <section class="redactor-form dyn-content">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div>
            <h3 class="delete-conf">"{{ article.title }}" will be deleted</h3>
            <hr>
            <form action="" method="post">
              {% csrf_token %}
              <input type="submit" value="Yes, I understand" class="btn btn-danger">
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/agency/article_detail.html
{% extends "base.html" %}

{% block content %}
  <section class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="banner-title regular-title">
            {{ article.title }}
          </h1>
        </div>
      </div>
    </div>
    {% load static %}
  </section>
  <section class="redactor-detail dyn-content">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
            {{ article.content }}
          </p>
          <hr>
          <p>Brought to your attention by
            {% for redactor in article.publishers.all %}
              <a href="{{ redactor.get_absolute_url }}"> {{ redactor.username }}</a>
            {% endfor %}
            <a href="{% url 'agency:article-delete' pk=article.id %}" class="btn btn-danger link-to-page">
              Delete
            </a>
            <a href="{% url 'agency:article-update' pk=article.id %}" class="btn btn-secondary link-to-page">
              Edit
            </a>
          </p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/agency/article_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>{{ object|yesno:"Edit,Create" }} Article</h1>
        </div>
      </div>
    </div>
    {% load static %}
  </section>
  <section class="redactor-form dyn-content">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div>
            <form action="" method="post" novalidate>
              {% csrf_token %}
              {{ form|crispy }}
              <input type="submit" value="Submit" class="btn btn-primary">
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/agency/article_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="banner-title regular-title">
            Articles
          </h1>
        </div>
      </div>
    </div>
    {% load static %}
  </section>
  <section class="table-lisot dyn-content">
    {% if article_list %}
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div>
              <form action="" method="get" class="form-inline">
                {{ search_form|crispy }}
                <input class="btn btn-primary" type="submit" value="🔍">
                <a href="{% url 'agency:article-create' %}" class="btn btn-primary link-to-page">
                  Add New Article
                </a>
              </form>
            </div>
            <table class="table table-borderless">
                <tr>
                  <th>ID</th>
                  <th>Title</th>
                  <th>Topic</th>
                </tr>
              {% for article in article_list %}
                <tr>
                  <td>
                    {{ article.id }}
                  </td>
                  <td>
                    <a href="{{ article.get_absolute_url }}">
                      {{ article.title }}
                    </a>
                  </td>
                  <td>
                    {{ article.topic.name }}
                  </td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    {% else %}
      <h5 class="no-data">There are no articles yet</h5>
    {% endif %}
  </section>

{% endblock %}

templates/agency/index.html
{% extends "base.html" %}

{% block content %}
  <section class="banner with-padding  mx-auto">
    <div class="container">
      <div class="row">
        <div class="text-center">
          <h1 class="banner-title">StinGEaR Auto News</h1>
          <p class="narrow-text">Welcome to StinGEaR, your go-to news portal for cutting-edge updates and in-depth analyses on the ever-evolving automotive landscape. We take you on a journey through the latest trends, innovations, and breakthroughs in the automotive industry, offering a comprehensive view of what drives tomorrow's roads. Join over 1.6 million developers around the world. </p>
        </div>
      </div>
    </div>
  </section>

  <section class="dyn-content with-padding">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-4">
          <h4>
            <a href="{% url 'agency:article-list' %}">
              {{ num_articles }}+<br>Articles
            </a>
          </h4>
          <p>Jump straight into reading</p>
        </div>

        <div class="col-md-4">
          <h4>
            <a href="{% url 'agency:redactor-list' %}">
              {{ num_redactors }}+<br>Redactors
            </a>
          </h4>
          <p>They all said hello</p>
        </div>

        <div class="col-md-4">
          <h4>
            <a href="{% url 'agency:topic-list' %}">
              {{ num_topics }}+<br>Topics
            </a>
          </h4>
          <p>What is this all about</p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/agency/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="banner-title regular-title">
            Redactors
          </h1>
        </div>
      </div>
    </div>
      {% load static %}
  </section>
  <section class="table-list dyn-content">
    {% if redactor_list %}
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div>
              <form action="" method="get" class="form-inline">
                {{ search_form|crispy }}
                <input class="btn btn-primary" type="submit" value="🔍">
                <a href="{% url 'agency:redactor-create' %}" class="btn btn-primary link-to-page text-left">
                  Create new Redactor
                </a>
              </form>
            </div>
            <table class="table table-borderless">
              <tr>
                <th>ID</th>
                <th>Username</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Years of experience</th>
              </tr>
            {% for redactor in redactor_list %}
              <tr>
                <td>{{ redactor.id }}</td>
                <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} </a></td>
                <td>{{ redactor.first_name }}</td>
                <td>{{ redactor.last_name }}</td>
                <td class=" text-center">{{ redactor.years_of_experience }}</td>
              </tr>
            {% endfor %}
            </table>
          </div>
        </div>
      </div>
    {% else %}
      <h5 class="no-data">There are no redactors in the agency.</h5>
    {% endif %}
  </section>
{% endblock %}

templates/agency/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="banner-title regular-title">
            Topics
          </h1>
        </div>
      </div>
    </div>
    {% load static %}
  </section>
  <section class="table-list dyn-content">
    {% if topic_list %}
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div>
              <form action="" method="get" class="form-inline">
                {{ search_form|crispy }}
                <input class="btn btn-primary" type="submit" value="🔍">
                <a href="{% url 'agency:topic-create' %}" class="btn btn-primary link-to-page">
                  Add New Topic
                </a>
              </form>
            </div>
            <table class="table table-borderless">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
              {% for topic in topic_list %}
              <tr>
                <td>
                  {{ topic.id }}
                </td>
                <td>
                  <a href="{% url 'agency:article-topic' topic=topic.name %}">
                    {{ topic.name }}
                  </a>
                </td>
                <td>
                  <a href="{% url 'agency:topic-update' pk=topic.id %}">
                    Edit
                  </a>
                </td>
                <td>
                  <a class="a-delete" href="{% url 'agency:topic-delete' pk=topic.id %}">
                    Delete
                  </a>
                </td>
              </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    {% else %}
      <div class="container">
        <h5 class="no-data">There are no topics</h5>
        <hr>
        <div>
          <form action="" method="get" class="form-inline">
            <a href="{% url 'agency:topic-create' %}" class="btn btn-primary link-to-page">
              Add New Topic
            </a>
          </form>
        </div>
      </div>
    {% endif %}
  </section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>StinGEaR Auto News</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  {% load static %}
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>

<body style="background-image: url('{% static 'images/bg11.jpg' %}'); background-size: cover;">
  {% block sidebar %}
    {% include "includes/sidebar.html" %}
  {% endblock %}

  {% block content %}{% endblock %}

  {% block pagination %}
    {% include "includes/pagination.html" %}
  {% endblock %}

  {% include "includes/footer.html" %}
</body>

</html>